spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-ar201mbc.sql.tencentcdb.com:21857/blog?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: XXXX
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      break-after-acquire-failure: true
      connection-error-retry-attempts: 3
  mapper:
    not-empty: false
    identity: MYSQL            
  freemarker:
    request-context-attribute: request
mybatis:
  config-location: classpath:/mybatis/config.xml
  mapper-locations: classpath:mapper/**/*.xml

