spring:
  datasource:
    url: jdbc:mysql://47.98.202.133:3306/blog?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234561
    driver-class-name: com.mysql.cj.jdbc.Driver
  mapper:
    not-empty: false
    identity: MYSQL            
  freemarker:
    request-context-attribute: request
mybatis:
  config-location: classpath:/mybatis/config.xml
  mapper-locations: classpath:mapper/**/*.xml

