spring:
  datasource:
    url: jdbc:mysql://47.98.202.133:3306/blog?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    config-location: classpath:/mybatis/config.xml
  mapper:
    not-empty: false
    identity: MYSQL
  freemarker:
    allow-request-override: true
    allow-session-override: true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    request-context-attribute: request
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
mybatis:
  config-location: classpath:/mybatis/config.xml

